### ISSUE TITLE
Fails in Core 2.2

### ISSUE THREAD

**Issue by weitzhandler** [xuzhg/MyAspNetCore#2]
Hi,

Please check out [my branch](https://github.com/weitzhandler/AspNetCore-1/tree/aspnetcore_2_2).

I just upgraded the packages to latest version and AspNetCore version to 2.2, and I'm getting this exception when calling `b.MapODataServiceRoute("odata", "odata", GetEdmModel());`:

>System.InvalidOperationException
  HResult=0x80131509
  Message=Cannot use 'Microsoft.AspNet.OData.Routing.ODataRoute' with Endpoint Routing.
  Source=Microsoft.AspNetCore.Mvc.Core
  StackTrace:
   at Microsoft.AspNetCore.Builder.MvcApplicationBuilderExtensions.UseMvc(IApplicationBuilder app, Action`1 configureRoutes)
   at BookStore.Startup.Configure(IApplicationBuilder app, IHostingEnvironment env) in D:\Users\Shimmy\Source\Repos\AspNetCore2\src\BookStore\BookStore\Startup.cs:line 45

[Here](https://github.com/weitzhandler/ODataDemo/tree/netcore22-repro)'s another repro, based on @hassanhabib's sample.

**Comment by weitzhandler** [comment]
Posted in the general repo: https://github.com/OData/odata.net/issues/1519
